services:
  server:
    container_name: 'server'
    build:
      context: ./server
    ports:
      - "4000:4000"
    networks:
      - app-network
    volumes:
      - './server:/usr/src/app'
  app:
    container_name: 'client'
    volumes:
      - "./app/src:/usr/src/app/src"
    build:
      context: ./app
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - server

networks:
  app-network:
    driver: bridge
